## Array Creation

In [1]:
import numpy as np
import random

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a_2d = np.random.rand(3,4)

In [5]:
a_2d

array([[0.53724325, 0.56879072, 0.57675382, 0.5524512 ],
       [0.60814313, 0.90526627, 0.91961623, 0.8792313 ],
       [0.29911724, 0.70918602, 0.36010806, 0.71535249]])

In [8]:
a_3d = np.zeros((2,3,4))

In [9]:
a_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array Operations

In [11]:
b = np.array([1,2,3])
c = np.array([4,5,6])

In [12]:
b+c

array([5, 7, 9])

In [13]:
c-b

array([3, 3, 3])

In [14]:
b*c

array([ 4, 10, 18])

In [15]:
c/b

array([4. , 2.5, 2. ])

In [16]:
a.mean()

2.0

In [18]:
np.median(a)

2.0

In [20]:
np.std(a)

0.816496580927726

In [25]:
new_arr = np.arange(12)

In [26]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
re_array = np.reshape(new_arr,(3,4))

In [38]:
re_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Array Indexing and Slicing

In [40]:
re_array[0]

array([0, 1, 2, 3])

In [43]:
re_array[-1]

array([ 8,  9, 10, 11])

In [45]:
a = np.arange(10)

In [46]:
np.flip(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
re_array[re_array>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

## Array Broadcasting

In [49]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
ar1d = np.array([1,2,3])
ar2d = np.array([[1,2,3],
               [4,5,6]])

In [54]:
ar1d*ar2d

array([[ 1,  4,  9],
       [ 4, 10, 18]])

## Linear Algebra

In [56]:
A = np.array([1,2])
B = np.array([4,5])

In [57]:
np.dot(A,B)

14

In [72]:
C = np.array([[1, 2],
              [3, 4]])

D = np.array([[5, 6],
              [7, 8]])


In [77]:
np.dot(C,D)

array([[19, 22],
       [43, 50]])

In [79]:
C_inv = np.linalg.inv(C)

In [80]:
C_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
det_C = np.linalg.det(C)

In [82]:
det_C

-2.0000000000000004

## Thank You